Main:
  # токен для подключения к API Тинькофф Инвестиции
  tinkoff_token: YOUR_TOKEN

  # токен для отправки сообщений в телеграм
  telegram_token: YOUR_TOKEN

  # ID телеграм канала
  telegram_chat_id: -1234567890


Subscription:
  # список инструментов для подписки
  csv_file_with_shares: "config/shares_example.csv"

  # подписка на свечи
  interval: 1h

  # интервал (в минутах) для расчета сигналов
  calculate_signals_interval: 15

  # интервал (в минутах) для ограничения отправки сообщений в чат
  signals_interval: 360

  # минимальное количество свечей для расчета (чем больше, тем точнее значение, но тем и сложнее расчет)
  candles_for_calculation_min_size: 100

  # путь до файла конфигурации сигналов
  signals_config_path: "config/signals_example.yaml"