Signal:
  # минимальное значение при котором осуществляется отправка сигнала
  # считается как сумма значений по всем индикаторам заданным в конфигурации
  # в представленном примере для того чтоб сигнал сработал сумма должна составлять 12 единиц
  # такое возможно только при условии, что индикатор KeltnerChannel с весом в 10 единиц даст положительный результат
  # + дополнительно сработают любые 2 из индикаторов RSI/STO/UO с весом 1
  min_weight: 12
  # описание сигнала
  description: Сигнал на покупку

# Relative Strength Index, Индекс относительной силы
# чем сильнее относительное движение цены вверх тем ближе значение индикатора к 100
# чем сильнее относительное движение цены вниз тем ближе значение индикатора к 0
# перекупленность/перепроданность — когда значение индикатора RSI ближе к отметке «100 %» или «0 %», соответственно
# Нельзя покупать, когда рынок уже перекуплен, то есть когда RSI выше уровня перекупленности.
# Нельзя продавать, когда рынок уже перепродан, то есть когда RSI ниже уровня перепроданности.
RSI:
  # вес для индикатора
  weight: 1
  # набор правил для индикатора
  rules:
    1:
      # предыдущее значение индикатора
      prev_value:
        # меньше
        lower: 35
      # текущее значение индикатора
      current_value:
        # меньше или равно
        lower_or_equal: 35
    2:
      # предыдущее значение индикатора
      prev_value:
        # меньше
        lower: 35
      # текущее значение индикатора
      current_value:
        # меньше или равно
        lower_or_equal: 35
      # условия сравнения
      compare:
        # текущее значение индикатора меньше предыдущего (сохраняется тренд на снижение)
        1: current_value<prev_value


# Stochastic oscillator, Стохастический осциллятор
# чем сильнее относительное движение цены вверх тем ближе значение индикатора к 100
# чем сильнее относительное движение цены вниз тем ближе значение индикатора к 0
# Пересечение отметки 20 % при снижении индикатора интерпретируется,
# как сигнал о вероятной остановке падения или даже начале роста цен.
# Пересечение отметки 80 % при росте индикатора интерпретируется,
# как сигнал о вероятной остановке роста или даже начале снижения цен
STO:
  # вес для индикатора
  weight: 1
  # набор правил для индикатора
  rules:
    1:
      # предыдущее значение индикатора
      prev_value:
        # больше 20
        upper: 20
      # текущее значение индикатора
      current_value:
        # меньше или равно
        lower_or_equal: 20
    2:
      # предыдущее значение индикатора
      prev_value:
        # меньше
        lower: 20
      # текущее значение индикатора
      current_value:
        # меньше или равно
        lower_or_equal: 20
      # условия сравнения
      compare:
        # текущее значение индикатора меньше предыдущего (сохраняется тренд)
        1: current_value<prev_value


# Ultimate Oscillator, Окончательный осциллятор
# Открыть длинную позицию, когда значение основного осциллятора находится ниже 43
# Закрыть длинную позицию, когда значение основного осциллятора находится ниже 73
UO:
  # вес для индикатора
  weight: 1
  # набор правил для индикатора
  rules:
    1:
      # предыдущее значение индикатора
      prev_value:
        upper: 40
      # текущее значение индикатора
      current_value:
        lower_or_equal: 40
    2:
      # предыдущее значение индикатора
      prev_value:
        # меньше
        lower: 40
      # текущее значение индикатора
      current_value:
        lower_or_equal: 40
      # условия сравнения
      compare:
        # текущее значение индикатора меньше предыдущего (сохраняется тренд)
        1: current_value<prev_value

# Keltner channel, Канал Кельтнера
# Пересечение ценовым показателем (максимальной ценой, или, в модификациях, на выбор: ценой закрытия или типичной ценой)
# верхней линии является сигналом к открытию длинной позиции
# и нижней (минимальной ценой, или на выбор: ценой закрытия или типичной ценой) — короткой
KeltnerChannel:
  # вес для индикатора
  weight: 10
  # набор правил для индикатора
  rules:
    1:
      # свое сообщение о срабатывании индикатора
      message: цена ушла ниже канала
      # условия сравнения
      compare:
        # текущая цена ниже значения индикатора
        1: price_current<current_l_band
        # предыдущая цена больше или равна предыдущему значению индикатора
        2: price_prev>=prev_l_band
    2:
      # свое сообщение о срабатывании индикатора
      message: цена ниже канала
      # условия сравнения
      compare:
        # текущая цена ниже значения индикатора
        1: price_current<current_l_band